# Generated by Django 4.2.3 on 2023-07-10 18:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerworkouts', '0004_alter_registerworkout_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workoutsessions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='Workout_Session',
        ),
    ]
