# Generated by Django 4.2.3 on 2023-07-05 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workoutsessions', '0001_initial'),
        ('exercises', '0001_initial'),
        ('registerworkouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistroEntrenamiento',
            new_name='RegisterWorkout',
        ),
    ]
