# Generated by Django 4.2.3 on 2023-07-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/')),
                ('muscular_group', models.CharField(max_length=100)),
                ('video', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
